### ISSUE TITLE
set-env is deprecated

### ISSUE THREAD

**Issue by mlliarm** [logtalk-actions/workflows#1]
Hello Paulo !

I used the file that runs tests in various backends, but it failed at [this](https://github.com/logtalk-actions/workflows/blob/e5e85498ccb0c2596a155976d5df50082dbe6590/testing_multiple_backends.yml#L32) line.

According to [Github](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) it seems that `set-env` isn't supported anymore, and if you'd like to use it you'd have to set the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. See [the error I got](https://github.com/mlliarm/ia/runs/4878299962?check_suite_focus=true#step:12:7) when I run that pipeline:

```
  echo "::set-env name=EXIT::0"
  shell: /usr/bin/bash -e {0}
  env:
    LOGTALKHOME: /usr/local/share/logtalk
    LOGTALKUSER: /home/runner/logtalk
Error: Unable to process command '::set-env name=EXIT::0' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

```

Cheers.

**Comment by mlliarm** [comment]
Just found [this](https://github.com/JamesIves/github-pages-deploy-action/issues/500#issuecomment-728375894) workaround. Testing it.

**Comment by pmoura** [comment]
Thanks for the bug report. Should be fixed now in the sample `testing.yml` and `testing_multiple_backends.yml` workflows.
